######docker-compose.override.yml######
version: "3.8"
services:
  app:
    build: .
    environment:
      UNA_VARIABLE: "Hola platzi"

    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    command: npx nodemon index.js
